#!/bin/ksh

[ $# -eq 2 ] || { echo "$(basename $0) <file> '<text>'" >&2; exit 1; }

file=$1
text="$2"

if [ -w $file ]; then
	latestver=$(pred $file) || exit 1;
else
	latestver=$(cleartool desc -short $file) || exit 1;
fi

startver=1
endver=${latestver##*/}
file=${latestver%/*}

verfound=''
while true; do
	ver=$(( (startver + endver)/2 ))
	while ((ver > 0)); do [ -f $file/$ver ] && break; let ver--; done
	((ver > 0)) || break
	#echo "($startver, $ver, $endver)" >&2
	if grep -F -q -e "$text" $file/$ver; then
		verfound=$ver;
		endver=$ver
		(( endver > startver )) || break
	else
		if (( (endver - startver) > 1 )); then startver=$ver;
		elif (( (endver - startver) == 1 )); then startver=$endver;
		else break;
		fi
	fi
done

if [ -n "$verfound" ]; then
	cleartool desc $file/$verfound >&2
	echo $file/$verfound
else
	echo "not found" >&2
	exit 1
fi


