#!/bin/ksh

# this script uploads files specified to ftp server

#FILE_DIR_NAME=${1%/*}
#FILE_BASE_NAME=${1##*/}
#[[ $FILE_DIR_NAME == $FILE_BASE_NAME ]] && FILE_DIR_NAME=''

usage()
{
	echo "$(basename ${0}) <filename>..." >&2
	exit 1 
}

fail()
{
	echo "$*" >&2
	exit 1
}

[[ $# -gt 0 ]] || usage
[[ -n "$PC_FTP_LOGNAME" ]] || fail 'please export PC_FTP_LOGNAME'
[[ -n "$PC_FTP_PASSWORD" ]] || fail 'please export PC_FTP_PASSWORD'

FTP_SERVER=''
FTP_LOGNAME=$PC_FTP_LOGNAME
FTP_PASSWD=$PC_FTP_PASSWORD

[[ -n $FTP_SERVER ]] || {
	# REMOTEHOST=10.0.0.18
	# SSH_CLIENT=::ffff:10.0.0.18 56287 22
	if [[ -n $REMOTEHOST ]]; then
		FTP_SERVER=$REMOTEHOST
	elif [[ -n $SSH_CLIENT ]]; then
		FTP_SERVER=$(echo ${SSH_CLIENT} | \
		sed -e "s/[^[:digit:]]*\([[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*\).*/\1/")
	fi
}
[[ -n $FTP_SERVER ]] || fail "unknown server, exit"

echo "check connection..."
ping -c 1 -W 2 $FTP_SERVER >> /dev/null || {
	echo "connection blocked, use CSL account to do authentication..."
	ftp $FTP_SERVER
}
echo "check connection after authentication..."
ping -c 1 -W 2 $FTP_SERVER >> /dev/null || fail "connection still blocked"

echo "connecting to ftp server $FTP_SERVER..."
echo ""

ftp -n $FTP_SERVER << SCRIPT
user $FTP_LOGNAME $FTP_PASSWD
binary
verbose

$(
for file in "$@"
do
	[[ -f $file ]] && {
		echo "lcd $(dirname ${file})"
		echo "put $(basename ${file})"
	}
done
)

quit

SCRIPT

exit 0

