#!/bin/ksh

tarfile=$HOME/vobs.tgz

dirs='
/vobs
'

excludes='
*/obj/* */tmp */lost+found */doc */lib */tools
*.o *.so *.a *.lib *.jar *.dll *.bin *.exe
*.map *.vsd *.img *.ts *.tmp *.bak *.pdf *.psd *.keep
*.rar *.zip *.bz2 *.gz *.bz
.cmake.state 
'

for dir in $dirs; do
	[ -d $dir ] || { echo "$dir not exist" >&2; exit 1; }
done

for ex in $excludes; do
	exopts="$exopts --exclude=$ex"
done

echo $exopts

mkdir -p $(dirname $tarfile)

tar $exopts -czvf $tarfile $dirs

