#!/bin/ksh

#KSH only
#The symbol |& causes asynchronous execution of the preceding pipeline 
#with a two-way pipe established to the parent shell; the standard input 
#and output of the spawned  pipeline  can  be written to and read from by 
#the parent shell by applying the redirection operators <& and >& with 
#arg p to commands and by using -p option of the built-in commands read 
#and print  described  later.

USER=''
PASSWORD=''

usage()
{
    echo "automatic telnet by using KSH's two-way FIFO" >&2
    echo "Usage: $(basename ${0}) <MACHINE>" >&2
    exit 1
}

[[ "$1" == "-h" ]] && usage

send_to_ne()
{
	print -p "$1\n" >&p
}

wait_ne_response()
{
	# wait 10 seconds for response
	timeout=10
	while read -t $timeout -p res <&p
	do
		echo $res
		echo $res | grep -q "$1" && return 0
	done
	echo "timeout to wait for MACHINE response" >&2
	exit 1
}

read_ne_response()
{
	while read -p res <&p
	do
		echo $res
	done
}

[ $# -eq 1 ] || usage

MACHINE=$1

telnet $MACHINE -l $USER |&

#login
wait_ne_response "Connected"
sleep 1
send_to_ne $PASSWORD
wait_ne_response "Last login:"
sleep 1

#group commands to be sent
cmds='{
ls /
exit
}
'
send_to_ne "$cmds"

read_ne_response

wait

