#!/bin/bash


usage()
{
    echo "get/put files from/to peer server"
    echo "Usage: $(basename ${0}) <get|put> <filename>..." >&2
    exit 1
}

[[ "$1" == "-h" ]] && usage

fail()
{
    echo "$*" >&2
    exit 1
}

do_ftp()
{
echo "ftp to $REMOTE_SERVER ..."
echo ""

ftp -n $REMOTE_SERVER << SCRIPT
user $REMOTE_LOGNAME $REMOTE_LOGIN_PASSWORD
binary
verbose
prompt

$(
for file in $FILES ;do
    echo "lcd $(dirname $file)"
    echo "$CMD $(basename $file)"
done
)

quit

SCRIPT
}


[[ $# -gt 1 ]] || usage

CMD=$1
[[ $CMD == 'get' || $CMD == 'put' ]] || usage

shift
FILES="$@"

[[ -n "$REMOTE_SERVER" ]] || fail 'please export REMOTE_SERVER'
[[ -n "$REMOTE_LOGNAME" ]] || fail 'please export REMOTE_LOGNAME'
[[ -n "$REMOTE_LOGIN_PASSWORD" ]] || fail 'please export REMOTE_LOGIN_PASSWORD'

do_ftp
