#!/bin/bash

usage()
{
    echo "remove c/c++ comments" >&2
    echo "Usage: $(basename $0) <file...>" >&2
    exit 1
}

[[ $# -gt 0 && "$1" != "-h" ]] || usage

for f in $*
do
    [[ -f $f ]] || { echo "$f is not file" >&2; continue; }

    _type=$(file $f)
    grep -q 'C source' <<< "$_type" || grep -q 'C++ source' <<< "$_type" || continue

    # do not touch file without comments
    grep -q '/\*\|//' $f || continue

    # delete single line comment //
    sed -i '/^[[:space:]]*\/\// d' $f
    sed -i 's#[[:space:]]*//.*##' $f

    # delete single line comment /**/
    sed -i '/^[[:space:]]*\/\*.*\*\/$/ d' $f
    sed -i 's#[[:space:]]*/\*.*\*/##' $f

    # delete multiple ine comment /**/
    awk '
    {
        if ($0~/\/\*/) {
            del = 1
            sub(/[[:space:]]*\/\*.*/, "")
            print
        }
        else
        {
           if (!del) print;
        }
    }
    /\*\// {
        del = 0
        sub(/.*\*\//, "")
        print
    }' $f > $f.temp

    mv $f.temp $f

    grep -q '/\*\|//' $f && echo "comments in $f are not cleaned" >&2
done
